[alembic]
script_location = alembic
version_locations = alembic/versions
timezone = UTC

[post_write_hooks]
# hooks are named .py files in the alembic/env_post_write_hooks directory
hooks =

[environment]
sqlalchemy.url = sqlite:///./dev.db