"""create_initial_schema

Revision ID: 56826e457b7d
Revises: 
Create Date: 2026-02-24 23:27:54.314271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56826e457b7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insureds',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insureds_email', 'insureds', ['email'], unique=False)
    op.create_index('idx_insureds_name', 'insureds', ['first_name', 'last_name'], unique=False)
    op.create_index('idx_insureds_tax_id', 'insureds', ['tax_id'], unique=False)
    op.create_index(op.f('ix_insureds_id'), 'insureds', ['id'], unique=False)
    op.create_table('payees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_document_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payees_email', 'payees', ['email'], unique=False)
    op.create_index('idx_payees_name', 'payees', ['name'], unique=False)
    op.create_index('idx_payees_tax_id', 'payees', ['tax_id'], unique=False)
    op.create_index(op.f('ix_payees_id'), 'payees', ['id'], unique=False)
    op.create_table('payment_routing_rules',
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('payee_filter', sa.Text(), nullable=True),
    sa.Column('payment_type_filter', sa.String(length=100), nullable=True),
    sa.Column('routing_target', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_payment_routing_rules_id'), 'payment_routing_rules', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_permissions_code', 'permissions', ['code'], unique=False)
    op.create_index('idx_permissions_role_id', 'permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('insured_id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.Enum('AUTO', 'PROPERTY', 'LIABILITY', 'WORKERS_COMP', 'HEALTH', 'OTHER', name='policytype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'CANCELLED', name='policystatus'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deductible_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_index('idx_policies_effective_date', 'policies', ['effective_date'], unique=False)
    op.create_index('idx_policies_insured_id', 'policies', ['insured_id'], unique=False)
    op.create_index('idx_policies_policy_number', 'policies', ['policy_number'], unique=False)
    op.create_index('idx_policies_status', 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('AGENT', 'UNDERWRITER', 'CLAIMS_ADJUSTER', 'FINANCE_MANAGER', 'RECOVERY_MANAGER', 'ADMIN', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_active', 'users', ['active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('idx_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('date_of_loss', sa.Date(), nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'CLOSED', 'PAID', 'DENIED', name='claimstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('injury_details', sa.Text(), nullable=True),
    sa.Column('carrier_involvement', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_index('idx_claims_claim_number', 'claims', ['claim_number'], unique=False)
    op.create_index('idx_claims_date_of_loss', 'claims', ['date_of_loss'], unique=False)
    op.create_index('idx_claims_policy_id', 'claims', ['policy_id'], unique=False)
    op.create_index('idx_claims_status', 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('coverages',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('coverage_type', sa.Enum('LIABILITY', 'COLLISION', 'COMPREHENSIVE', 'UNINSURED_MOTORIST', 'MEDICAL_PAYMENTS', 'OTHER', name='coveragetype'), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deductible_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coverages_policy_id', 'coverages', ['policy_id'], unique=False)
    op.create_index(op.f('ix_coverages_id'), 'coverages', ['id'], unique=False)
    op.create_table('endorsements',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('endorsement_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_endorsements_policy_id', 'endorsements', ['policy_id'], unique=False)
    op.create_index(op.f('ix_endorsements_id'), 'endorsements', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_policy_id', 'locations', ['policy_id'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.Enum('ACH', 'WIRE', 'CARD', 'STRIPE', 'GLOBAL_PAYOUTS', name='paymentmethodtype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('routing_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_holder_name', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_methods_payee_id', 'payment_methods', ['payee_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_table('tax_reportable_payments',
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_form_type', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('tax_id_type', sa.String(length=20), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_reportable_payments_payee_id', 'tax_reportable_payments', ['payee_id'], unique=False)
    op.create_index(op.f('ix_tax_reportable_payments_id'), 'tax_reportable_payments', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('idx_vehicles_policy_id', 'vehicles', ['policy_id'], unique=False)
    op.create_index('idx_vehicles_vin', 'vehicles', ['vin'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('claim_adjustments',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=100), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_claim_adjustments_claim_id', 'claim_adjustments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_adjustments_id'), 'claim_adjustments', ['id'], unique=False)
    op.create_table('claim_level_policies',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('insured_name', sa.String(length=200), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=True),
    sa.Column('coverage_details', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_claim_level_policies_claim_id', 'claim_level_policies', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_level_policies_id'), 'claim_level_policies', ['id'], unique=False)
    op.create_table('external_estimates',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('estimate_number', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('line_item_description', sa.Text(), nullable=True),
    sa.Column('item_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_payable', sa.Boolean(), nullable=False),
    sa.Column('additional_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_estimates_claim_id', 'external_estimates', ['claim_id'], unique=False)
    op.create_index(op.f('ix_external_estimates_id'), 'external_estimates', ['id'], unique=False)
    op.create_table('other_carrier_info',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('claim_number', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('payment_info', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_other_carrier_info_claim_id', 'other_carrier_info', ['claim_id'], unique=False)
    op.create_index(op.f('ix_other_carrier_info_id'), 'other_carrier_info', ['id'], unique=False)
    op.create_table('reserve_lines',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('reserve_type', sa.String(length=100), nullable=False),
    sa.Column('total_reserve', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_eroding', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reserve_lines_claim_id', 'reserve_lines', ['claim_id'], unique=False)
    op.create_index(op.f('ix_reserve_lines_id'), 'reserve_lines', ['id'], unique=False)
    op.create_table('scheduled_payments',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('payee_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DUE', 'PAID', 'OVERDUE', name='scheduledpaymentstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_payments_claim_id', 'scheduled_payments', ['claim_id'], unique=False)
    op.create_index('idx_scheduled_payments_status', 'scheduled_payments', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_payments_id'), 'scheduled_payments', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_number', sa.String(length=100), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('reserve_line_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('ACH', 'WIRE', 'CARD', 'STRIPE', 'GLOBAL_PAYOUTS', name='paymentmethodtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PROCESSING', 'COMPLETED', 'FAILED', 'VOIDED', 'REVERSED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_eroding', sa.Boolean(), nullable=False),
    sa.Column('is_tax_reportable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['reserve_line_id'], ['reserve_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.create_index('idx_payments_claim_id', 'payments', ['claim_id'], unique=False)
    op.create_index('idx_payments_payee_id', 'payments', ['payee_id'], unique=False)
    op.create_index('idx_payments_payment_number', 'payments', ['payment_number'], unique=False)
    op.create_index('idx_payments_policy_id', 'payments', ['policy_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('payment_deductions',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=100), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_deductions_payment_id', 'payment_deductions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_deductions_id'), 'payment_deductions', ['id'], unique=False)
    op.create_table('payment_details',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('detail_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_details_payment_id', 'payment_details', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_details_id'), 'payment_details', ['id'], unique=False)
    op.create_table('payment_documents',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_documents_payment_id', 'payment_documents', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_documents_id'), 'payment_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_documents_id'), table_name='payment_documents')
    op.drop_index('idx_payment_documents_payment_id', table_name='payment_documents')
    op.drop_table('payment_documents')
    op.drop_index(op.f('ix_payment_details_id'), table_name='payment_details')
    op.drop_index('idx_payment_details_payment_id', table_name='payment_details')
    op.drop_table('payment_details')
    op.drop_index(op.f('ix_payment_deductions_id'), table_name='payment_deductions')
    op.drop_index('idx_payment_deductions_payment_id', table_name='payment_deductions')
    op.drop_table('payment_deductions')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_policy_id', table_name='payments')
    op.drop_index('idx_payments_payment_number', table_name='payments')
    op.drop_index('idx_payments_payee_id', table_name='payments')
    op.drop_index('idx_payments_claim_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_scheduled_payments_id'), table_name='scheduled_payments')
    op.drop_index('idx_scheduled_payments_status', table_name='scheduled_payments')
    op.drop_index('idx_scheduled_payments_claim_id', table_name='scheduled_payments')
    op.drop_table('scheduled_payments')
    op.drop_index(op.f('ix_reserve_lines_id'), table_name='reserve_lines')
    op.drop_index('idx_reserve_lines_claim_id', table_name='reserve_lines')
    op.drop_table('reserve_lines')
    op.drop_index(op.f('ix_other_carrier_info_id'), table_name='other_carrier_info')
    op.drop_index('idx_other_carrier_info_claim_id', table_name='other_carrier_info')
    op.drop_table('other_carrier_info')
    op.drop_index(op.f('ix_external_estimates_id'), table_name='external_estimates')
    op.drop_index('idx_external_estimates_claim_id', table_name='external_estimates')
    op.drop_table('external_estimates')
    op.drop_index(op.f('ix_claim_level_policies_id'), table_name='claim_level_policies')
    op.drop_index('idx_claim_level_policies_claim_id', table_name='claim_level_policies')
    op.drop_table('claim_level_policies')
    op.drop_index(op.f('ix_claim_adjustments_id'), table_name='claim_adjustments')
    op.drop_index('idx_claim_adjustments_claim_id', table_name='claim_adjustments')
    op.drop_table('claim_adjustments')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index('idx_vehicles_vin', table_name='vehicles')
    op.drop_index('idx_vehicles_policy_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_tax_reportable_payments_id'), table_name='tax_reportable_payments')
    op.drop_index('idx_tax_reportable_payments_payee_id', table_name='tax_reportable_payments')
    op.drop_table('tax_reportable_payments')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_index('idx_payment_methods_payee_id', table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index('idx_locations_policy_id', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_endorsements_id'), table_name='endorsements')
    op.drop_index('idx_endorsements_policy_id', table_name='endorsements')
    op.drop_table('endorsements')
    op.drop_index(op.f('ix_coverages_id'), table_name='coverages')
    op.drop_index('idx_coverages_policy_id', table_name='coverages')
    op.drop_table('coverages')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index('idx_claims_status', table_name='claims')
    op.drop_index('idx_claims_policy_id', table_name='claims')
    op.drop_index('idx_claims_date_of_loss', table_name='claims')
    op.drop_index('idx_claims_claim_number', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index('idx_policies_status', table_name='policies')
    op.drop_index('idx_policies_policy_number', table_name='policies')
    op.drop_index('idx_policies_insured_id', table_name='policies')
    op.drop_index('idx_policies_effective_date', table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index('idx_permissions_role_id', table_name='permissions')
    op.drop_index('idx_permissions_code', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_payment_routing_rules_id'), table_name='payment_routing_rules')
    op.drop_table('payment_routing_rules')
    op.drop_index(op.f('ix_payees_id'), table_name='payees')
    op.drop_index('idx_payees_tax_id', table_name='payees')
    op.drop_index('idx_payees_name', table_name='payees')
    op.drop_index('idx_payees_email', table_name='payees')
    op.drop_table('payees')
    op.drop_index(op.f('ix_insureds_id'), table_name='insureds')
    op.drop_index('idx_insureds_tax_id', table_name='insureds')
    op.drop_index('idx_insureds_name', table_name='insureds')
    op.drop_index('idx_insureds_email', table_name='insureds')
    op.drop_table('insureds')
    # ### end Alembic commands ###
